AllCops:
  RunRailsCops: true

# コメントをAscii文字に限定するか
Style/AsciiComments:
  Enabled: false

# 1行の最大文字列長を制限するか
Style/LineLength:
  Max: 160

# %でのsprintfを無効にするか
Style/FormatString:
  Enabled: false

# メソッド定義の行数を制限するか
Style/MethodLength:
  Max: 50

# 複数行の空白を制限するか
Style/EmptyLines:
  Enabled: false

# top-classでのコメントを必須にするか
Style/Documentation:
  Enabled: false

# 1行if文を強制するか
Style/IfUnlessModifier:
  Enabled: false

# 文字列をシングルクォートに強制するか
Style/StringLiterals:
  Enabled: false

# ruby1.9形式のハッシュ形式(:key => value)を無効にするか
Style/HashSyntax:
  Enabled: false

# 文字列のみの配列作成時に%w()形式を強制するか
Style/WordArray:
  MinSize: 5
