AllCops:
  # Includes:
  #   - Rakefile
  #   - config.ru
  Exclude:
    - vendor/**
    - db/migrate/**

Encoding:
  Enabled: false

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 1行の最大長制限を緩和
LineLength:
  Enabled: true
  # Max: 79
  Max: 250

# %でのsprintfを許容
FavorSprintf:
  Enabled: false

# メソッド定義の行数制限
MethodLength:
  # Max: 10
  Max: 150

# 複数行の空白
EmptyLines:
  Enabled: false

# 複数行ブロックに{}の使用を不可
Blocks:
  Enabled: true

# class内での不要なselfの利用制限
RedundantSelf:
  Enabled: false

# top-classでのコメント?
Documentation:
  Enabled: false

# 1行if文にしなくてもよい
IfUnlessModifier:
  Enabled: false

# { }の周りにスペースをいれなくてもいい
SpaceAroundBraces:
  Enabled: false

# シングルクォートの推奨を無効
StringLiterals:
  Enabled: false

HashSyntax:
  Enabled: false

CollectionMethods:
  Enabled: false

Semicolon:
  Enabled: false

BlockAlignment:
  Enabled: false

EndAlignment:
  Enabled: false

RescueModifier:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

WordArray:
  Enabled: false

NumericLiterals:
  Enabled: false

RedundantReturn:
  Enabled: false

ReduceArguments:
  Enabled: false

RescueException:
  Enabled: false
